### ISSUE TITLE
Merge traildbs

### ISSUE THREAD

**Issue by ChrisJamesC** [Sqooba/traildb-java#25]
Following the discussion on https://github.com/traildb/traildb/issues/104 we have decided with @aholyoke to merge this project with https://github.com/aholyoke/traildb-java. 

To do so we plan on: 
- keeping the architecture of this project 
- use https://github.com/aholyoke/traildb-java's way to iterate over trails in order to conserve performance. 
- move this project to traildb/traildb-java once we have a first version that is satisfying. 

For the iteration across trails and events, there are 3 approaches: 
1. use iterators where we create objects on each iteration (how it is right now in our project)
2. use pointers as in C (how it's implemented on https://github.com/aholyoke/traildb-java)
3. use iterators on pointers, which could lead to errors if we don't make copies before storing objects in variables. 

For now we will go with 2 and then see if we can find an elegant solution like 3.

**Comment by Shastick** [comment]
Archiving the repo, closing open issues.
