### ISSUE TITLE
Artifact version number.

### ISSUE THREAD

**Issue by Nennya** [Sqooba/traildb-java#6]
The file versions.properties contains the artifact version that will be used when pushing to packagecloud.io, however, this version does not correspond to the one in the pom.xml but it should(have to?).

**Comment by fatum** [comment]
Hi Nennya!

This is can be potential problem for sbt? Unfortunately i cannot fetch deps from packagecloud

```scals
resolvers += "Nennya-traildb-java" at "https://packagecloud.io/Nennya/traildb-java/maven2"
libraryDependencies += "io.sqooba" % "traildb" % "1.0.0"
```

```
[info] Resolving io.sqooba#traildb;1.0.0 ...
[info] Failed to read descriptor dependency: io.sqooba#traildb;1.0.0 {compile=[default(compile)]} from public, Failed to read artifact descriptor for io.sqooba:traildb:jar:1.0.0
[info] Failed to read descriptor dependency: io.sqooba#traildb;1.0.0 {compile=[default(compile)]} from Sonatype OSS Snapshots, Failed to read artifact descriptor for io.sqooba:traildb:jar:1.0.0
[info] Failed to read descriptor dependency: io.sqooba#traildb;1.0.0 {compile=[default(compile)]} from Nennya-traildb-java, Failed to read artifact descriptor for io.sqooba:traildb:jar:1.0.0
[warn] 	module not found: io.sqooba#traildb;1.0.0
```

**Comment by Nennya** [comment]
Hello!

I think I have identified the problem. For some reason the jar that is on packagecloud does not contain the pom, which I think makes sbt fail. When using maving a warning is generated but it does not fail.

**Comment by fatum** [comment]
Thank you, repo is ok now!

**Comment by Nennya** [comment]
Now the version in the pom never changes but the pushed jar version depends on the git tagged commit number.
